baseurl = "http://mdl.life/"
title = ""
languageCode = "en-us"
theme = "hugo-zen"


DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = "false"

[Languages]
  [Languages.en]
    weight = 1
  [Languages.zh]
    weight = 2
  [Languages.zh-hant]
    weight = 3
  [Languages.ru]
    weight = 2

[Params]
  logo = "https://ipfs.io/ipfs/QmdfEPfbk5wbWJPYcLRNk9n847J1Zva7gDXR7LsyyhyrGS"
